# Generated by Django 4.1 on 2022-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
    ]
