# Generated by Django 4.1 on 2022-09-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_remove_post_is_custom_remove_post_is_dev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dev',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_tester',
        ),
    ]
