# Generated by Django 4.1 on 2022-09-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_remove_user_is_custom_remove_user_is_dev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='Lorem Ipsum', max_length=500),
        ),
    ]
