# Generated by Django 4.1 on 2022-09-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0011_userfollowing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('to_follow', 'who_follows')},
        ),
    ]
