# Generated by Django 4.1 on 2022-09-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0015_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='None'),
        ),
    ]
