# Generated by Django 4.1 on 2022-09-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0016_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='Put an image here'),
        ),
    ]
