# Generated by Django 4.1 on 2022-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0018_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
