# Generated by Django 4.1 on 2023-02-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0020_usertouserconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
